### ISSUE TITLE
what the sigma

### ISSUE THREAD

**Issue by nmsderp** [dumorando/bapiv2#1]
![image](https://github.com/dumorando/bapiv2/assets/130254323/6bf7b8ce-bd83-428e-985c-b3149159908d)
![image](https://github.com/dumorando/bapiv2/assets/130254323/0e98c3ea-8244-4623-9a23-e05506dd0083)
![image](https://github.com/dumorando/bapiv2/assets/130254323/0538b375-3fa9-42e6-ae7f-895de6af92f1)

**Comment by dumorando** [comment]
*that is an issue with the hosted instance please go to discussions for that*

okay ill fix it
